Add common event format plugin
observIQ/stanza-plugins pull request #328
Opened 2021-09-13 03:26 UTC by ericwholt

This plugin adds option to parse common event format logs. Currently it is not possible to parse the extensions without the addition of an operator. Currently supports syslog prefix with timestamp matching `Jan 02 15:04:05 ` and a hostname.

2021-09-15 13:55 UTC, jsirianni requested changes
Some thoughts
```
name --> message
device_ --> labels
hostname --> resource
signature. --> ??
version --> ??
```

Also, I will be building a key value parser, so we can handle extenssions.

2021-09-22 02:51 UTC, ericwholt commented on plugins/common_event_format.yaml
> +      layout: 'Jan 02 15:04:05'
Done

2021-09-25 19:07 UTC, ericwholt commented
Removed key_value parser. Extensions format allows to many variations to parse using the parser.

2021-09-28 21:20 UTC, jsirianni commented
Lets promote device_vendor / device_version to resources

2021-09-29 16:53 UTC, jsirianni approved these changes

2021-09-29 16:53 UTC, jsirianni commented
```json
{
  "timestamp": "2021-09-11T08:26:10Z",
  "severity": 70,
  "severity_text": "10",
  "labels": {
    "device": "threatmanager",
    "file_name": "cef.log",
    "log_type": "cef",
    "plugin_id": "common_event_format",
    "version": "0"
  },
  "resource": {
    "device_vendor": "security",
    "device_version": "1.0",
    "hostname": "zurich"
  },
  "record": {
    "extensions": "src=10.0.0.1 dst=2.1.2.2 spt=1232 ",
    "message": "worm successfully stopped",
    "signature_id": "100"
  }
}
```

2021-09-29 16:55 UTC, merged