Update Titles and uwsgi field name
observIQ/stanza-plugins pull request #350
Opened 2021-10-01 01:33 UTC by ericwholt

Remove Log Parser from titles parameter in `codeigniter`, `common_event_format`, and `uwsgi`. Also change `headers` field in `uwsgi` to `headers_count`

2021-10-01 16:56 UTC, jsirianni requested changes
For uwsgi, lets replace `request_time` with `request_timestamp`.

2021-10-03 21:08 UTC, ericwholt commented
@jsirianni I am unsure what you are referring to here. I do not see a `request_time` group name being parsed.

2021-10-04 16:07 UTC, jsirianni commented
> @jsirianni I am unsure what you are referring to here. I do not see a `request_time` group name being parsed.

Sorry, this field comes from the json format. We will update the doc.

2021-10-04 16:09 UTC, jsirianni approved these changes

2021-10-04 16:13 UTC, merged