Syslog documentation
observIQ/stanza-plugins pull request #384
Opened 2021-12-08 15:56 UTC by jsirianni

2021-12-09 14:51 UTC, Dylan-M requested changes
I only see examples with IPv4, do we support IPv6? If so, some examples using IPv6 should be included as well.

2021-12-09 14:51 UTC, Dylan-M commented on docs/syslog.md
> +Input Entry (sent with `echo "<message here>" | nc -u localhost 514`)
Rather than <message here>, this should be whatever your message is in the output example. Currently that is "user connected"

2021-12-09 14:51 UTC, Dylan-M commented on docs/syslog.md
> +Input Entry (sent with `echo "<message here>" | nc -u 10.99.1.10 514`, use your machine's IP address)
Same as previous comment, the <message here> should be matched to the sample output

2021-12-09 14:51 UTC, Dylan-M commented on docs/syslog.md
> +Input Entry (sent with `echo "<message here>" | nc localhost 5140`)
And again :)

2021-12-09 14:51 UTC, Dylan-M commented on docs/syslog.md
> +Input Entry (sent with `echo "<message here>" | nc localhost 5140`)
Same here

2022-02-02 21:46 UTC, asenkowski requested changes
Do we want to add one more example concerning TLS support as well as adding the TLS fields to the configuration fields section?

2022-02-02 21:55 UTC, asenkowski approved these changes

2022-02-02 21:56 UTC, merged