Update couchdb to gain parity with google
observIQ/stanza-plugins pull request #404
Opened 2022-02-25 15:23 UTC by JonathanWamsley

Example log 
```log
[info] 2022-01-12T16:52:56.998128Z nonode@nohost <0.216.0> -------- Apache CouchDB has started. Time to relax.
```

Example output
```json
{
    "timestamp": "2022-01-12T16:52:56.998128Z",
    "severity": 30,
    "severity_text": "info",
    "labels": {
        "file_name": "couchdb.log",
        "log_type": "couchdb",
        "plugin_id": "couchdb"
    },
    "record": {
        "host": "nohost",
        "message": "\u003c0.216.0\u003e -------- Apache CouchDB has started. Time to relax.\n",
        "node": "nonode",
        "pid": "0.216.0"
    }
}
```

Example access log
```log
[notice] 2021-12-02T23:36:42.555157Z nonode@nohost <0.17165.1> a5f585a0d3 localhost:5984 127.0.0.1 otelu PUT /oteld 201 ok 16
```
Example output
```json
{
    "timestamp": "2021-12-02T23:36:42.555157Z",
    "severity": 30,
    "severity_text": "notice",
    "labels": {
        "file_name": "couchdb.log",
        "log_type": "couchdb",
        "plugin_id": "couchdb"
    },
    "record": {
        "host": "nohost",
        "http_request_remoteIp": "127.0.0.1",
        "http_request_requestMethod": "PUT",
        "http_request_responseSize": "16",
        "http_request_serverIp": "localhost:5984",
        "http_request_status": "201",
        "message": "otelu PUT /oteld 201 ok 16",
        "node": "nonode",
        "path": "/oteld",
        "pid": "0.17165.1",
        "remote_user": "otelu",
        "status_message": "ok"
    }
}
```

Example error log
```log
[error] 2022-01-12T16:53:03.094488Z nonode@nohost emulator -------- Error in process <0.463.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
```

Example error output
```json
{
    "timestamp": "2022-01-12T16:53:03.094488Z",
    "severity": 60,
    "severity_text": "error",
    "labels": {
        "file_name": "couchdb.log",
        "log_type": "couchdb",
        "plugin_id": "couchdb"
    },
    "record": {
        "host": "nohost",
        "message": "emulator -------- Error in process \u003c0.463.0\u003e with exit value:\n{database_does_not_exist,[{mem3_shards,load_shards_from_db,\"_users\",[{file,\"src/mem3_shards.erl\"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,\"src/mem3_shards.erl\"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,\"src/mem3_shards.erl\"},{line,403}]},{mem3_shards,for_docid,3,[{file,\"src/mem3_shards.erl\"},{line,96}]},{fabric_doc_open,go,3,[{file,\"src/fabric_doc_open.erl\"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,\"src/chttpd_auth_cache.erl\"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,\"src/chttpd_auth_cache.erl\"},{line,145}]}]}\n",
        "node": "nonode",
        "pid": "0.463.0"
    }
}
```

2022-03-03 16:14 UTC, jsirianni requested changes
I get errors with the following log file
```
[info] 2022-01-12T16:52:56.998128Z nonode@nohost <0.216.0> -------- Apache CouchDB has started. Time to relax.
[notice] 2021-12-02T23:36:42.555157Z nonode@nohost <0.17165.1> a5f585a0d3 localhost:5984 127.0.0.1 otelu PUT /oteld 201 ok 16
[error] 2022-01-12T16:53:03.094488Z nonode@nohost emulator -------- Error in process <0.463.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
[info] 2022-01-12T16:52:56.998128Z nonode@nohost <0.216.0> -------- Apache CouchDB has started. Time to relax.
```
Error
```json
{
  "timestamp": "2022-03-03T11:13:54.213831047-05:00",
  "severity": 0,
  "labels": {
    "file_name": "in",
    "log_type": "couchdb",
    "plugin_id": "couchdb"
  },
  "record": "[error] 2022-01-12T16:53:03.094488Z nonode@nohost emulator -------- Error in process <0.463.0> with exit value:\n{database_does_not_exist,[{mem3_shards,load_shards_from_db,\"_users\",[{file,\"src/mem3_shards.erl\"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,\"src/mem3_shards.erl\"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,\"src/mem3_shards.erl\"},{line,403}]},{mem3_shards,for_docid,3,[{file,\"src/mem3_shards.erl\"},{line,96}]},{fabric_doc_open,go,3,[{file,\"src/fabric_doc_open.erl\"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,\"src/chttpd_auth_cache.erl\"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,\"src/chttpd_auth_cache.erl\"},{line,145}]}]}\n"
}
{
  "level": "error",
  "timestamp": "2022-03-03T11:13:54.213-0500",
  "message": "error while writing entry: regex pattern does not match",
  "operator_id": "$.couchdb.couchdb_input",
  "operator_type": "file_input"
}
```

Config
```yaml
pipeline:
- type: couchdb
  file_path: ./in
  start_at: beginning

- type: stdout
```

2022-03-14 19:00 UTC, JonathanWamsley commented
> I get errors with the following log file
> 
> ```
> [info] 2022-01-12T16:52:56.998128Z nonode@nohost <0.216.0> -------- Apache CouchDB has started. Time to relax.
> [notice] 2021-12-02T23:36:42.555157Z nonode@nohost <0.17165.1> a5f585a0d3 localhost:5984 127.0.0.1 otelu PUT /oteld 201 ok 16
> [error] 2022-01-12T16:53:03.094488Z nonode@nohost emulator -------- Error in process <0.463.0> with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
> [info] 2022-01-12T16:52:56.998128Z nonode@nohost <0.216.0> -------- Apache CouchDB has started. Time to relax.
> ```
> 
> Error
> 
> ```json
> {
>   "timestamp": "2022-03-03T11:13:54.213831047-05:00",
>   "severity": 0,
>   "labels": {
>     "file_name": "in",
>     "log_type": "couchdb",
>     "plugin_id": "couchdb"
>   },
>   "record": "[error] 2022-01-12T16:53:03.094488Z nonode@nohost emulator -------- Error in process <0.463.0> with exit value:\n{database_does_not_exist,[{mem3_shards,load_shards_from_db,\"_users\",[{file,\"src/mem3_shards.erl\"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,\"src/mem3_shards.erl\"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,\"src/mem3_shards.erl\"},{line,403}]},{mem3_shards,for_docid,3,[{file,\"src/mem3_shards.erl\"},{line,96}]},{fabric_doc_open,go,3,[{file,\"src/fabric_doc_open.erl\"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,\"src/chttpd_auth_cache.erl\"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,\"src/chttpd_auth_cache.erl\"},{line,145}]}]}\n"
> }
> {
>   "level": "error",
>   "timestamp": "2022-03-03T11:13:54.213-0500",
>   "message": "error while writing entry: regex pattern does not match",
>   "operator_id": "$.couchdb.couchdb_input",
>   "operator_type": "file_input"
> }
> ```
> 
> Config
> 
> ```yaml
> pipeline:
> - type: couchdb
>   file_path: ./in
>   start_at: beginning
> 
> - type: stdout
> ```

I am running v1.6.1 darwin amd64 and the error log is parsing correctly as:


The Output:
```json
{
    "timestamp": "2022-01-12T16:53:03.094488Z",
    "severity": 60,
    "severity_text": "error",
    "labels": {
        "file_name": "couchdb.log",
        "log_type": "couchdb",
        "plugin_id": "couchdb"
    },
    "record": {
        "host": "nohost",
        "message": "emulator -------- Error in process \u003c0.463.0\u003e with exit value:\n{database_does_not_exist,[{mem3_shards,load_shards_from_db,\"_users\",[{file,\"src/mem3_shards.erl\"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,\"src/mem3_shards.erl\"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,\"src/mem3_shards.erl\"},{line,403}]},{mem3_shards,for_docid,3,[{file,\"src/mem3_shards.erl\"},{line,96}]},{fabric_doc_open,go,3,[{file,\"src/fabric_doc_open.erl\"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,\"src/chttpd_auth_cache.erl\"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,\"src/chttpd_auth_cache.erl\"},{line,145}]}]}\n",
        "node": "nonode",
        "pid": "0.463.0"
    }
}
```


Do I need to be on a different version or something? I ran the mac quick install

2022-03-17 19:36 UTC, jsirianni commented
I may have made a mistake, looks good to me now.

2022-03-17 19:36 UTC, jsirianni approved these changes

2022-03-24 13:28 UTC, merged